### ISSUE TITLE
java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by coret** [CLARIAH/burgerLinker#16]
I get an `java.lang.NumberFormatException: null` error on the closure function (on the [smh dataset](https://www.openarch.nl/exports/nt/#civ)):
```
START: Computing the transitive closure
START: Loading HDT dataset...
*DONE: Loading HDT dataset [runtime: 1.22 s]

--------
- Number of statements in this dataset: 10876758
- Number of distinct subjects: 1737181
- Number of distinct predicates: 19
- Number of distinct objects: 4955699
--------



Saving individual links (Within_B_M) for file: output/within_b_m-maxLev-3-fixed/results/within-B-M-maxLev-3-fixed.csv
Within_B_M  10% │███████████▊                                                                                                     │  7000/67239 links (0:00:00 / 0:00:03)
java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at iisg.amsterdam.burgerlinker.LinksCSV.saveIndividualLink(LinksCSV.java:327)
        at iisg.amsterdam.burgerlinker.processes.Closure.saveLinksIndividuals_Within_B_M(Closure.java:437)
        at iisg.amsterdam.burgerlinker.processes.Closure.saveIndividualLinksToFile(Closure.java:369)
        at iisg.amsterdam.burgerlinker.processes.Closure.computeClosure(Closure.java:74)
        at iisg.amsterdam.burgerlinker.processes.Closure.<init>(Closure.java:64)
        at iisg.amsterdam.burgerlinker.Controller.computeClosure(Controller.java:399)
        at iisg.amsterdam.burgerlinker.Controller.runProgram(Controller.java:109)
        at iisg.amsterdam.burgerlinker.App.run(App.java:91)
        at iisg.amsterdam.burgerlinker.App.main(App.java:60)
*DONE: Computing the transitive closure [runtime: 1.93 s]

```

and lines 6998-7002 of within-B-M-maxLev-3-fixed.csv look like:
```
39181360,769249840,21,0,0,0,0,0,0,2,2,2,1,1,1,1,1,1,26
39183980,23298760,21,5,3,3,0,N.A,N.A,1,1,1,1,1,1,N.A,N.A,N.A,59
39183980,1101553180,21,1,0,1,0,N.A,N.A,1,1,1,1,1,1,N.A,N.A,N.A,43
39187920,291518130,21,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,32
39194620,207752480,21,0,0,0,0,0,0,2,2,2,1,1,1,1,1,1,26
```

Line 7000 shows the number 1.101.553.180, but this is a valid integer, max. Java int being 2.147.483.647 (thousand seperators added for readability).

**Comment by coret** [comment]
I have made a new SAMH dataset (14-06-2022), only difference with the 11-06-2020 version being other integers for registrationID's and personID's. The 14-06-2022 smh file results in a succesfull closure (no NumberFormatException)!

I'll keep the 14-06-2022 smh file on the [Open Archives export page](https://www.openarch.nl/exports/nt/#civ) to reproduce this error.

FYI: my test person "abraham johannes (van) loon" in the finalDataset [shown as graph](https://www.goudatijdmachine.nl/sparql/graphs-visualizations?saved=89527656031e44e59ea8fb96b2aeaef5).
